### ISSUE TITLE
Target not working

### ISSUE THREAD

**Issue by AUT0CR4T** [trclassic92/qb-simplefarming#26]
I installed your script, but target is not working, when I right-click on anything nothing happens and this error appears on F8 log "SCRIPT ERROR: @qb-target/client.lua:397: attempt to index a nil value (field '?')"

**Comment by trclassic92** [comment]
Can you send a screenshot of what you are trying to target

**Comment by bigramb0** [comment]
> Can you send a screenshot of what you are trying to target

https://i.imgur.com/s0Iyw1t.png

https://i.imgur.com/MiJIUq7.jpeg

This issue occurs when DrawSprites is enabled in qb-target, nothing is able to be targeted. When you right click the target, the following error displays.

https://i.imgur.com/PlvLQOG.png

**Comment by trclassic92** [comment]
Drawsprite doesn't work with this script if you want to use drawspirte I recommend using ox_target and then converting the script to support ox_target since ox target is heavily used now. I am going to probably end up making this resource support it or just redoing this script completely one day. Not sure when that day will be since I am busy doing other things

**Comment by abdel1touimi** [comment]
math.random(1,99999999999999999999999)/10 for laziness :joy:
